name = "ACE Arsenal Extended"
prefix = "aceax"
author = "GrueArbre"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "logo.paa"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]