name: Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT
      
    - name: DEBUG
      run: ls -la optionals/compat_rhs/XtdGearInfos/rhs_weapon/CfgWeapons/
      
    - name: Build Mod
      run: hemtt build
